name: serverless-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest     
      - run: pip install poetry
      - run: poetry install
      - run: curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - run: apt-get install -y nodejs
      - run: npm install -g serverless && npm install serverless-python-requirements serverless-pseudo-parameters
      - run: npm install --save-dev serverless-plugin-warmup serverless-prune-plugin
      - run: sls deploy

  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}